#!/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="cdk deploy"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

cdk deploy \
 --parameters githubUserName=$GITHUB_USERNAME \
 --parameters githubPersonalTokenSecretName=$GITHUB_TOKEN \
