#!/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="confirm-github-token"
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"


aws secretsmanager get-secret-value \
 --secret-id /github-token \
 --version-stage AWSCURRENT
 
export GITHUB_TOKEN=$(aws ssm get-parameter --name /github-token --with-decryption --query "Parameter.Value" --output text)